---
name: Docker CI

on:
  push:
    tags: 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Ensure Dockerfile is up to date
        run: |
          mv Dockerfile Dockerfile.bak
          make Dockerfile
          cmp Dockerfile Dockerfile.bak

      - name: Build the Docker image
        run: make build

  push:
    needs: build

    runs-on: ubuntu-latest

    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build the Docker image
        run: make build

      - name: Login to DockerHub
        run: echo ${{ secrets.DH_ACCESS_TOKEN }} | docker login -u ${{ secrets.DH_USERNAME }} --password-stdin

      - name: Push image to DockerHub
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          echo "pushing tag $VERSION"
          docker tag cucalc turinginst/cucalc:$VERSION
          docker push turinginst/cucalc:$VERSION

          echo "pushing tag latest"
          docker tag cucalc turinginst/cucalc:latest
          docker push turinginst/cucalc:latest
